// Note: In this example, no try-catch is given so an assertion error of the kind given below will be the output.

console.clear();
const assert = require("assert");

let x = 4;
let y = 5;

assert(x > y);

//Note: Text Highlighted is the assertion error.
